allowBuilds:
  better-sqlite3: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - "@actual-app/api@26.9.0"
  - "@actual-app/core@26.9.0"
onlyBuiltDependencies: '["better-sqlite3"]'
